services:
  mysql:
    container_name: mysql
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - mysql:/data/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    ports:
      - "3306:3306"
    restart: unless-stopped
  cassandra:
    container_name: cassandra
    image: cassandra:4.0
    ports:
      - 9042:9042
    volumes:
      - cassandra:/data/cassandra
  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - "9411:9411"
#    networks:
#      - spring
#  eureka-server:
#    image: dlim2012/tiny-url_eureka-server:latest
#    container_name: eureka-server
#    ports:
#      - "8761:8761"
#    environment:
#      - SPRING_PROFILES_ACTIVE=docker
#    networks:
#      - spring
#  apigw:
#    image: dlim2012/tiny-url_apigw:latest
#    container_name: apigw
#    ports:
#      - "8080:8080"
#    environment:
#      - SPRING_PROFILES_ACTIVE=docker
#    networks:
#      - spring
networks:
  spring:
    driver: bridge

volumes:
  mysql:
  cassandra: