server:
  port: 8081

rsa:
  private-key: classpath:certs/private.pem
  public-key: classpath:certs/public.pem
spring:
  application:
    name: appuser
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tiny_url
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
  zipkin:
    base-url: http://localhost:9411

eureka:
  client:
    server-url:
      defaultZone: http://localhost:8761/eureka
    enabled: true

hostname: http://127.0.0.1