server:
  port: 8081
  error:
    include-message: always
    include-binding-errors: always

rsa:
  private-key: classpath:certs/private.pem
  public-key: classpath:certs/public.pem
spring:
  application:
    name: appuser
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tiny_url
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
  cache:
    type: redis
    cache-names:
      - cache1
      - cache2
    redis:
      time-to-live: 600000
      cache-null-values: true
  redis:
    host: localhost
    port: 6379
  zipkin:
    base-url: http://localhost:9411

eureka:
  client:
    server-url:
      defaultZone: http://localhost:8761/eureka
    enabled: true

hostname: http://76.23.247.67
