server:
  port: 8080

spring:
  application:
    name: api-gateway
  zipkin:
    base-url: http://localhost:9411
  cloud:
    gateway:
      routes:
        - id: appuser-auth (0)
          uri: lb://APPUSER
          predicates:
            - Path=/
          filters:
            - SetPath=/api/v1/user/urls
        - id: appuser-auth
          uri: lb://APPUSER
          predicates:
            - Path=/api/v1/auth/**
        - id: appuser-user
          uri: lb://APPUSER
          predicates:
            - Path=/api/v1/user/**
        - id: shorturl-api
          uri: lb://SHORTURL
          predicates:
            - Path=/api/v1/shorturl/**
        - id: shorturl-redirect
          uri: lb://SHORTURL
          predicates:
            - Path=/{short_path}
          filters:
            - SetPath=/api/v1/shorturl/redirect/{short_path}

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    registry-with-eureka: true