server:
  port: 8000

spring:
  application:
    name: api-gateway
  zipkin:
    base-url: http://localhost:9411
  cloud:
    gateway:
      routes:
        - id: url
          uri: lb://URL
          predicates:
            - Path=/**
        - id: appuser
          uri: lb://APPUSER
          predicates:
            - Path=/api/v1/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    registry-with-eureka: true