server:
  port: 8082
spring:
  application:
    name: longurl

  cassandra_longurl:
    contactPoints: 127.0.0.1
    port: 9044
    keyspace: tiny_url
    schemaAction: CREATE_IF_NOT_EXISTS
    request:
      timeout: 10s
    connection:
      connect-timeout: 10s
      init-query-timeout: 10s
  zipkin:
    base-url: http://zipkin:9411

eureka:
  client:
    server-url:
      defaultZone: http://eureka:8761/eureka
    enabled: true

domain: "http://example.com"