server:
  port: 8083
spring:
  application:
    name: token
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tiny_url
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true
  zipkin:
    base-url: http://localhost:9411

eureka:
  client:
    server-url:
      defaultZone: http://localhost:8761/eureka
    enabled: true