server:
  port: 8082
  error:
    include-message: always
    include-binding-errors: always

rsa:
  public-key: classpath:certs/public.pem

spring:
  application:
    name: shorturl

  cassandra:
    contact-points: localhost
    port: 9042
    keyspace: tiny_url
    schema-action: CREATE_IF_NOT_EXISTS
    request:
      timeout: 10s
    connection:
      connect-timeout: 10s
      init-query-timeout: 10s
  zipkin:
    base-url: http://localhost:9411

eureka:
  client:
    server-url:
      defaultZone: http://localhost:8761/eureka
    enabled: true

hostname: http://76.23.247.67
