server:
  port: 8083
spring:
  application:
    name: shorturl

  cassandra_shorturl:
    contactPoints: localhost
    port: 9043
    keyspace: tiny_url
    schemaAction: CREATE_IF_NOT_EXISTS
    request:
      timeout: 10s
    connection:
      connect-timeout: 10s
      init-query-timeout: 10s
  zipkin:
    base-url: http://localhost:9411

eureka:
  client:
    server-url:
      defaultZone: http://localhost:8761/eureka
    enabled: true

domain: "http://example.com"