server:
  port: 8081
spring:
  application:
    name: accomodation
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/tiny_url
    username: root
    password: G2ak-JxG
  jpa:
    hibernate:
      ddl-auto: create-drop
#      ddl-auto: update
    generate-ddl: true
    show-sql: true