server:
  port: 8081
spring:
  application:
    name: token
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql:3307/tiny_url
    username: root
    password: G2ak-JxG
  jpa:
    hibernate:
      ddl-auto: create-drop
#      ddl-auto: update
    generate-ddl: true
    show-sql: true
  zipkin:
    base-url: http://zipkin:9411

eureka:
  client:
    server-url:
      defaultZone: http://eureka:8761/eureka
    fetch-registry: true # default: true
    register-with-eureka: true # default: true
    enabled: true # default: true